function Hd = filter
%FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 09-Oct-2024 14:54:41

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 20;  % Sampling Frequency

Fpass = 3.375;             % Passband Frequency
%Fstop = 5.625;             % Stopband Frequency
Fstop = 4.625;             % Stopband Frequency
Dpass = 0.0011512920378;   % Passband Ripple
Dstop = 3.1622776602e-05;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
